#include <LiquidCrystal.h> //INCLUSÃO DE BIBLIOTECA

LiquidCrystal lcd(12, 11, 5, 4, 3, 2); //PORTAS DO ARDUINO QUE SÃO UTILIZADAS PELO DISPLAY LCD

void setup(){
 lcd.begin(16, 2); //SETA A QUANTIDADE DE COLUNAS(16) E O NÚMERO DE LINHAS(2) DO DISPLAY. EM SUMA: UMA MATRIZ DE 16 COLUNAS E 2 LINHAS
 pinMode(6,OUTPUT); //DECLARA QUE O PINO 6 É UMA SAÍDA
 analogWrite(6,50); //ESCREVE O VALOR 50 NA PORTA 6 (CONTROLE DO CONTRASTE VIA PWM)
}
void loop() {
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("Tuts tuts tuts"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("Quero ve"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(900);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("Hoje vai ter festinha"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("321"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(900);
}
