#include <LiquidCrystal.h> //INCLUSÃO DE BIBLIOTECA

LiquidCrystal lcd(12, 11, 5, 4, 3, 2); //PORTAS DO ARDUINO QUE SÃO UTILIZADAS PELO DISPLAY LCD
int tempo = 50;

void setup(){
 lcd.begin(16, 2); //SETA A QUANTIDADE DE COLUNAS(16) E O NÚMERO DE LINHAS(2) DO DISPLAY. EM SUMA: UMA MATRIZ DE 16 COLUNAS E 2 LINHAS
 pinMode(6,OUTPUT); //DECLARA QUE O PINO 6 É UMA SAÍDA
 analogWrite(6,50); //ESCREVE O VALOR 50 NA PORTA 6 (CONTROLE DO CONTRASTE VIA PWM)
}
void loop() {
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print(">"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("               <"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("              <-"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("-->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("             <--"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("--->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("            <---"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("---->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("           <----"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("----->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("          <-----"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("------>"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("         <------"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("------>"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("         <------"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
 lcd.setCursor(0,0);  //SETA A POSIÇÃO EM QUE O CURSOR INCIALIZA(LINHA 1)
 lcd.print("------->"); //ESCREVE A PALAVRA "MASTERWALKERSHOP" NA PRIMEIRA LINHA DO DISPLAY LCD
 lcd.setCursor(0,1); //SETA A POSIÇÃO EM QUE O CURSOR RECEBE O TEXTO A SER MOSTRADO(LINHA 2)
 lcd.print("        <-------"); //ESCREVE A PALAVRA "DISPLAY LCD 16X2" NA SEGUNDA LINHA DISPLAY LCD
 delay(tempo);
 lcd.clear();
}
